<script setup></script>
<template>
    <article>
        <div class="content">
            <h1>Supervised Fine-Tuning</h1>
            <p>
                The model is put through finishing school to learn how to be a good assistant.
            </p>
            <img src="@/assets/images/supervised-fine-tuning.png" alt="supervised-fine-tuning" />
            <ul>
                <li>
                    Repeat the same token guessing game, but now learningfrom examples of conversations between a user a helpful AI assistant.
                    <ul>
                        <li>The first examples were created manually.</li>
                        <li>Now a lot of the training data is generated by existing LLMs.</li>
                    </ul>
                </li>
                <li>The model learns what answering a question looks like, and how to follow instructions.</li>
                <li>Also when to refuse instructions
                    <ul>
                        <li>Taught not to give instructions on making a bomb, even if the user asks nicely.</li>
                        <li>This is where a model becomes "aligned" - meaning it does what we want it to do.</li>
                        <li>The issue of alignment is more complex and nuanced!</li>
                    </ul>
                </li>
            </ul>
        </div>
    </article>
</template>
<style lang="scss" scoped>
article {
    height: 100%;
    text-wrap: pretty;
    padding: 30px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;

    padding: 0 160px;

    .content > ul > li {
        margin-bottom: 3rem;
    }
}
h1 {
    text-align: center;
}
img {
    float: right;
    max-width: 600px;
    margin-left: 20px;
}
</style>